### ISSUE TITLE
Windows10에서 어떻게 실행하는지 모르겠습니다

### ISSUE THREAD

**Issue by SungChulByun** [kakao-recruit/2019-blind-2nd-elevator#5]
작년에 여쭤보신 분 처럼 Go\src 에 넣어서 해봤는데 잘 안되네요...

![image](https://user-images.githubusercontent.com/48064992/64923122-dd476c80-d811-11e9-8135-b97302b39c98.png)

Go는 처음이라 어떻게 하는지 잘 모르겠습니다 도와주세요...

GOPATH를 조금씩 바꿔봐도 잘 안되네요

**Comment by SungChulByun** [comment]
![image](https://user-images.githubusercontent.com/48064992/64924428-9a8c9100-d81f-11e9-853b-55b1d65f4d61.png)

현재 이렇습니다ㅠㅠ 도와주세요

**Comment by kwangswei** [comment]
현재 GOPATH 위치가 어딘가요?
$GOPATH/src/2019-blind-2nd-elevator/elevator/cmd/elevator
위치가 맞는지요?

go mod 와 쫑이 난걸로 보아 C:\Users\user 가 GOPATH 로 지정이 되어 있는 것 같습니다. 

1) GOPATH 가 아닌 곳에서 go mod 를 사용해서 작업하거나,
2) GOPATH 내의 go.mod 파일을 지우고 GOPATH 하에 소스를 두어 빌드하거나,

하셔야 할 것 같습니다.

**Comment by kwangsung-ha** [comment]
Docker 를 이용하여 실행하는 방법을 추가했습니다.
Docker 설치 후 한 번 시도해보시고, 문제 생기면 이슈 재오픈 부탁드립니다.

$ git clone https://github.com/kakao-recruit/2019-blind-2nd-elevator.git
$ cd 2019-blind-2nd-elevator
$ docker build . -t elevator
$ docker run -p 8000:8000 elevator

**Comment by spide333** [comment]
![image](https://user-images.githubusercontent.com/48064992/65049792-51fce100-d9a1-11e9-9e06-f5c559b048b4.png)


docker build . -t elevator 까지는 잘 되는데
docker run -p 8000:8000 elevator 에서 다음과 같이 실행이 안됩니다.

**Comment by kwangsung-ha** [comment]
docker build 가 제대로 되지 않은 것 같습니다.

docker images 를 통해 docker image 가 제대로 생성되었는지 확인해보시고, 
다시 해보시기 바랍니다.

간단한 docker 사용법이나 go build 방법 등은 스스로 찾아서 해보시기 바랍니다.
