### ISSUE TITLE
go get./ 에서 오류가 납니다.

### ISSUE THREAD

**Issue by dotaku1992** [kakao-recruit/2019-blind-2nd-elevator#7]
경로는 
![image](https://user-images.githubusercontent.com/35699122/94131120-7f277d80-fe98-11ea-92cf-5a20fe01f27c.png) 이렇게 설정되어있습니다. git clone명령어가 아닌 알집으로 받아서 압축해재후 복사했습니다.
그 후에 윈도우 cmd창에서 C:\>cd Go\src\2019-blind-2nd-elevator-master\elevator\cmd\elevator\ 입력후에 go get ./ 을 쳤는데
C:\Go\src\2019-blind-2nd-elevator-master\elevator\cmd\elevator>is not a package in module rooted at C:\Go\src
이렇게 결과가 뜨는데 계속 삭제하고 지우면서 계속 해보는데 어떤걸 알아봐야하는 건가요?

**Comment by dotaku1992** [comment]
$GOPATH 가 cmd창에서 go env에서 나오는 GOPATH 주소를 말하는건가요?
아니면 https://golang.org/doc/install 여기서 다운받을때 다운받았던 장소를 말하는건가요? 설치방법이 뭔가 자세히 영상이나 사진으로 나왔으면 좋겠습니다

**Comment by dotaku1992** [comment]
해결했습니다. git bash로 하니까 되네요 일반 cmd창으로는 계속 동일 에러가 뜨네요

**Comment by TaeBeomShin** [comment]
감사합니다
